Repository knu-Capstone2025/Capstone-Interview-Assistant, pull requests merged in 2025-05, with the labels that each got.

#55 chore: 서버 응답 플래그 생성 및 사용자 전송 제한
  src/InterviewAssistant.Web/Components/Pages/Home.razor
  test/InterviewAssistant.AppHost.Tests/Components/Pages/HomeTests.cs
Labels: ✨ Feature

#51 feat: 링크 다운로드 기능 구현
  src/InterviewAssistant.ApiService/Program.cs
  src/InterviewAssistant.ApiService/Services/Implementation/UrlContentDownloader.cs
  src/InterviewAssistant.ApiService/Services/Interface/IUrlContentDownloader.cs
  test/InterviewAssistant.ApiService.Tests/Common/MockHttpMessageHandler.cs
  test/InterviewAssistant.ApiService.Tests/Common/MockHttpMessageHandlerResponse.cs
  test/InterviewAssistant.ApiService.Tests/Services/UrlContentDownloaderTest.cs
Labels: ✨ Feature

#58 Feat: 업로드된 이력서 및 채용공고의 저장을 위한 인메모리 DB 기능 구현
  src/InterviewAssistant.ApiService/Data/InterviewDbContext.cs
  src/InterviewAssistant.ApiService/InterviewAssistant.ApiService.csproj
  src/InterviewAssistant.ApiService/Models/JobDescriptionEntry.cs
  src/InterviewAssistant.ApiService/Models/ResumeEntry.cs
  src/InterviewAssistant.ApiService/Program.cs
  src/InterviewAssistant.ApiService/Repositories/IInterviewRepository.cs
  src/InterviewAssistant.ApiService/Repositories/InterviewRepository.cs
  test/InterviewAssistant.ApiService.Tests/Repositories/InterviewRepositoryTests.cs
Labels: ✨ Feature

#53 Deploy: Azure Application Insights를 활용한 애플리케이션 모니터링 기능 도입
  .github/workflows/azure-dev.yml
  src/InterviewAssistant.AppHost/InterviewAssistant.AppHost.csproj
  src/InterviewAssistant.AppHost/Program.cs
  src/InterviewAssistant.ServiceDefaults/Extensions.cs
  src/InterviewAssistant.ServiceDefaults/InterviewAssistant.ServiceDefaults.csproj
Labels: 🚀 Deploy

#64 Feat: 이력서 및 채용공고 URL 프론트엔드-백엔드 연동 구현
  src/InterviewAssistant.Web/Clients/ChatApiClient.cs
  src/InterviewAssistant.Web/Components/Pages/Home.razor
  src/InterviewAssistant.Web/Services/ChatService.cs
  src/InterviewAssistant.Web/wwwroot/css/chat.css
  src/InterviewAssistant.Web/wwwroot/js/chatFunctions.js
  test/InterviewAssistant.AppHost.Tests/Components/Pages/HomeTests.cs
  test/InterviewAssistant.Web.Tests/Clients/ChatApiClientTests.cs
  test/InterviewAssistant.Web.Tests/Services/ChatServiceTests.cs
Labels: ✨ Feature

#63 Feat: 면접 챗봇 에이전트 구현
  src/InterviewAssistant.ApiService/Agents/InterviewAgents/InterviewAgent.yaml
  src/InterviewAssistant.ApiService/Delegates/PostChatCompletionDelegate.cs
  src/InterviewAssistant.ApiService/Delegates/PostChatInterviewDataDelegate.cs
  src/InterviewAssistant.ApiService/InterviewAssistant.ApiService.csproj
  src/InterviewAssistant.ApiService/Program.cs
  src/InterviewAssistant.ApiService/Repositories/IInterviewRepository.cs
  src/InterviewAssistant.ApiService/Repositories/InterviewRepository.cs
  src/InterviewAssistant.ApiService/Services/KernelService.cs
  test/InterviewAssistant.ApiService.Tests/Delegates/PostChatCompletionDelegateTests.cs
  test/InterviewAssistant.ApiService.Tests/Services/KernelServiceTest.cs
Labels: ✨ Feature

#75 Refactor: 이력서 및 채용공고 저장 시 세션별로 ID를 구분하도록 수정
  src/InterviewAssistant.ApiService/Delegates/PostChatCompletionDelegate.cs
  src/InterviewAssistant.ApiService/Delegates/PostChatInterviewDataDelegate.cs
  src/InterviewAssistant.ApiService/Repositories/IInterviewRepository.cs
  src/InterviewAssistant.ApiService/Repositories/InterviewRepository.cs
  src/InterviewAssistant.Common/Models/ChatRequest.cs
  src/InterviewAssistant.Common/Models/InterviewDataRequest.cs
  test/InterviewAssistant.ApiService.Tests/Delegates/PostChatCompletionDelegateTests.cs
Labels: ♻️ Refactoring

#74 Deploy: ci-cd pipeline 내부에서 main으로의 push의 경우, 테스트가 실패할 시 깃액션이 실패하도록 조치
  .github/workflows/azure-dev.yml
Labels: 🚀 Deploy

#79 Feat: Prompt injection attack 필터링
  src/InterviewAssistant.ApiService/Agents/InterviewAgents/InterviewAgent.yaml
  src/InterviewAssistant.Web/Components/Pages/Home.razor
Labels: ✨ Feature

#83 Chore: 테스트 실패시 깃액션 실패하도록 main push 이외의 상황에도 적용
  .github/workflows/azure-dev.yml
Labels: 🚀 Deploy

#78 Feat: MarkitDown MCP 적용
  .github/workflows/azure-dev.yml
  .gitignore
  README.md
  src/InterviewAssistant.ApiService/Delegates/PostChatInterviewDataDelegate.cs
  src/InterviewAssistant.ApiService/Extensions/AspireUrlParserExtensions.cs
  src/InterviewAssistant.ApiService/InterviewAssistant.ApiService.csproj
  src/InterviewAssistant.ApiService/Program.cs
  src/InterviewAssistant.ApiService/Services/KernelService.cs
  src/InterviewAssistant.AppHost/Program.cs
  test/InterviewAssistant.ApiService.Tests/InterviewAssistant.ApiService.Tests.csproj
  test/InterviewAssistant.ApiService.Tests/Services/KernelServiceTest.cs
  test/InterviewAssistant.AppHost.Tests/Components/Pages/HomeTests.cs
Labels: ✨ Feature

#81 Feat: 프론트에서 Guid 생성 및 백 연동
  src/InterviewAssistant.ApiService/Repositories/InterviewRepository.cs
  src/InterviewAssistant.Web/Components/Pages/Home.razor
  src/InterviewAssistant.Web/Program.cs
  src/InterviewAssistant.Web/Services/ChatService.cs
  test/InterviewAssistant.AppHost.Tests/Components/Pages/HomeTests.cs
  test/InterviewAssistant.Web.Tests/Services/ChatServiceTests.cs
Labels: ✨ Feature

#86 Feat: 전역 예외 핸들러 구현
  src/InterviewAssistant.ApiService/Middlewares/GlobalExceptionHandler.cs
  src/InterviewAssistant.ApiService/Program.cs
  test/InterviewAssistant.ApiService.Tests/Integration/GlobalExceptionHandlerTestServerTests.cs
  test/InterviewAssistant.ApiService.Tests/InterviewAssistant.ApiService.Tests.csproj
  test/InterviewAssistant.ApiService.Tests/Middlewares/GlobalExceptionHandlerTests.cs
Labels: ✨ Feature

#87 Refactor: IME 중복 키 이벤트 문제 해결
  src/InterviewAssistant.Web/Components/Pages/Home.razor
  test/InterviewAssistant.AppHost.Tests/Components/Pages/HomeTests.cs
Labels: 😡 Bug Fix
