Repository knu-Capstone2025/Capstone-Interview-Assistant, pull requests merged in 2025-04, with the labels that each got.

#21 Feat: github models, azure openai 연결을 위한 코드 구성
  src/InterviewAssistant.ApiService/Extensions/ServiceExtensions.cs
  src/InterviewAssistant.ApiService/InterviewAssistant.ApiService.csproj
  src/InterviewAssistant.ApiService/Program.cs
  src/InterviewAssistant.ApiService/Services/AI/Implementations/AIModelService.cs
  src/InterviewAssistant.ApiService/Services/AI/Implementations/OpenAIChatClient.cs
  src/InterviewAssistant.ApiService/Services/AI/Interfaces/IAIModelService.cs
  src/InterviewAssistant.ApiService/Services/AI/Interfaces/IChatClient.cs
Labels: ✨ Feature

#30 Deploy: CI/CD workflow 환경변수 주입 추가
  .github/workflows/ci-cd-workflow.yml
Labels: 🚀 Deploy

#27 Chore: 서버 응답을 공백을 기준으로 나누어 출력하지 않도록 수정
  src/InterviewAssistant.Web/Clients/ChatApiClient.cs
  src/InterviewAssistant.Web/Components/Pages/Home.razor
Labels: 😡 Bug Fix

#31 feat: azd를 활용한 배포환경 구성 및 CI/CD 파이프라인에 통합
  .github/workflows/azure-dev.yml
  .gitignore
  azure.yaml
Labels: 🚀 Deploy

#24 Feat: 이력서 및 채용공고 URL 등록 UI
  src/InterviewAssistant.Web/Components/Pages/Home.razor
  src/InterviewAssistant.Web/wwwroot/css/chat.css
  test/InterviewAssistant.AppHost.Tests/Components/Pages/HomeTests.cs
Labels: ✨ Feature

#25 Feat: Semantic Kernel 등록
  src/InterviewAssistant.ApiService/InterviewAssistant.ApiService.csproj
  src/InterviewAssistant.ApiService/Program.cs
  src/InterviewAssistant.ApiService/Services/KernelService.cs
  src/InterviewAssistant.AppHost/InterviewAssistant.AppHost.csproj
  src/InterviewAssistant.AppHost/Program.cs
  src/InterviewAssistant.AppHost/appsettings.json
  test/InterviewAssistant.ApiService.Tests/InterviewAssistant.ApiService.Tests.csproj
  test/InterviewAssistant.ApiService.Tests/Services/KernelServiceTest.cs
Labels: ✨ Feature

#36 feat: 채팅 엔드포인트 기능 구현
  src/InterviewAssistant.ApiService/Delegates/PostChatCompletionDelegate.cs
  src/InterviewAssistant.ApiService/Program.cs
  src/InterviewAssistant.Common/Models/ChatRequest.cs
  test/InterviewAssistant.ApiService.Tests/Delegates/PostChatCompletionDelegateTests.cs
Labels: ✨ Feature

#39 chore: 사용하지 않는 인터페이스 삭제 + Azure OpenAI 커넥션스트링 추가
  .github/workflows/azure-dev.yml
  scripts/Get-OpenAIDetails.ps1
  scripts/New-OpenAIs.ps1
  scripts/Purge-CognitiveServices.ps1
  src/InterviewAssistant.ApiService/Extensions/ServiceExtensions.cs
  src/InterviewAssistant.ApiService/Program.cs
  src/InterviewAssistant.ApiService/Services/AI/Implementations/AIModelService.cs
  src/InterviewAssistant.ApiService/Services/AI/Implementations/OpenAIChatClient.cs
  src/InterviewAssistant.ApiService/Services/AI/Interfaces/IAIModelService.cs
  src/InterviewAssistant.ApiService/Services/AI/Interfaces/IChatClient.cs
  src/InterviewAssistant.AppHost/InterviewAssistant.AppHost.csproj
  src/InterviewAssistant.Web/Components/Pages/Home.razor
Labels: 🚀 Deploy, 📦 Environment, ♻️ Refactoring

#40 chore: 깃헙 액션 버그 수정 + 리드미 파일 수정
  .github/workflows/azure-dev.yml
  .gitignore
  README.md
  scripts/README.md
Labels: 😡 Bug Fix, 🚀 Deploy, 📖 Docs, 🚑 HotFix!

#41 feat: 프론트엔드 화면에서 API연동 구현
  src/InterviewAssistant.Web/Clients/ChatApiClient.cs
  src/InterviewAssistant.Web/Components/Pages/Home.razor
  test/InterviewAssistant.Web.Tests/Clients/ChatApiClientTests.cs
  test/InterviewAssistant.Web.Tests/Clients/FakeHttpMessageHandler.cs
Labels: ✨ Feature

#45 chore: Markdig 패키지 및 마크다운 인라인 렌더링 함수 추가
  src/InterviewAssistant.Web/Components/Pages/Home.razor
  src/InterviewAssistant.Web/InterviewAssistant.Web.csproj
Labels: ♻️ Refactoring
