Repository knu-Capstone2025/Capstone-Interview-Assistant, pull requests merged in 2025-03, with the labels that each got.

#7 Deploy: CI/CD를 위한 Git Action 로직 초기 구현
  .github/workflows/ci-cd-workflow.yml
  test/InterviewAssistant.Web.Tests/InterviewAssistant.Web.Tests.csproj
Labels: 🚀 Deploy

#15 Feat: 공통 모델 추가
  src/InterviewAssistant.Common/Models/ChatRequest.cs
  src/InterviewAssistant.Common/Models/ChatResponse.cs
  src/InterviewAssistant.Common/Models/InterviewDataRequest.cs
Labels: ✨ Feature

#13 Feat: 이력서 및 채용공고 URL 입력 API 명세 작성
  src/InterviewAssistant.ApiService/InterviewAssistant.ApiService.csproj
  src/InterviewAssistant.ApiService/Program.cs
Labels: 📡 API

#9 Feat: 채팅 기능 API 명세 작성
  src/InterviewAssistant.ApiService/Delegates/PostChatCompletionDelegate.cs
  src/InterviewAssistant.ApiService/Delegates/PostChatInterviewDataDelegate.cs
  src/InterviewAssistant.ApiService/Endpoints/ChatCompletionEndpoint.cs
  src/InterviewAssistant.ApiService/InterviewAssistant.ApiService.csproj
  src/InterviewAssistant.ApiService/Program.cs
  src/InterviewAssistant.ApiService/Properties/launchSettings.json
  test/InterviewAssistant.ApiService.Tests/InterviewAssistant.ApiService.Tests.csproj
Labels: 📡 API

#10 Feat: 홈화면 UI 기본 구조 개발
  src/InterviewAssistant.ApiService/Delegates/PostChatCompletionDelegate.cs
  src/InterviewAssistant.AppHost/InterviewAssistant.AppHost.csproj
  src/InterviewAssistant.Common/InterviewAssistant.Common.csproj
  src/InterviewAssistant.Web/Clients/ChatApiClient.cs
  src/InterviewAssistant.Web/Components/App.razor
  src/InterviewAssistant.Web/Components/Layout/NavMenu.razor
  src/InterviewAssistant.Web/Components/Pages/Counter.razor
  src/InterviewAssistant.Web/Components/Pages/Home.razor
  src/InterviewAssistant.Web/Components/Pages/Weather.razor
  src/InterviewAssistant.Web/Components/_Imports.razor
  src/InterviewAssistant.Web/InterviewAssistant.Web.csproj
  src/InterviewAssistant.Web/Models/ChatMessage.cs
  src/InterviewAssistant.Web/Program.cs
  src/InterviewAssistant.Web/Services/ChatService.cs
  src/InterviewAssistant.Web/WeatherApiClient.cs
  src/InterviewAssistant.Web/wwwroot/css/chat.css
  src/InterviewAssistant.Web/wwwroot/js/chatFunctions.js
  test/InterviewAssistant.ApiService.Tests/InterviewAssistant.ApiService.Tests.csproj
  test/InterviewAssistant.AppHost.Tests/Components/Pages/HomeTests.cs
  test/InterviewAssistant.AppHost.Tests/InterviewAssistant.AppHost.Tests.csproj
  test/InterviewAssistant.Common.Tests/InterviewAssistant.Common.Tests.csproj
  test/InterviewAssistant.Web.Tests/Clients/ChatApiClientTests.cs
  test/InterviewAssistant.Web.Tests/InterviewAssistant.Web.Tests.csproj
  test/InterviewAssistant.Web.Tests/Services/ChatServiceTests.cs
  test/InterviewAssistant.Web.Tests/UnitTest1.cs
Labels: ✨ Feature
